// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using StrongKingJames.Data;

#nullable disable

namespace StrongKingJames.Data.Migrations
{
    [DbContext(typeof(BibleDbContext))]
    [Migration("20260721131734_AddNotes")]
    partial class AddNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StrongKingJames.Core.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Testament")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Reference");

                    b.HasIndex("Type");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.StrongsEntry", b =>
                {
                    b.Property<string>("Number")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KjvUsage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Number");

                    b.ToTable("strongs_entries", (string)null);
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer");

                    b.Property<string>("OsisId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OsisId")
                        .IsUnique();

                    b.HasIndex("BookId", "Chapter", "VerseNumber");

                    b.ToTable("verses", (string)null);
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.VerseWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("StrongsNumber")
                        .HasColumnType("text");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer");

                    b.Property<string>("WordText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StrongsNumber");

                    b.HasIndex("VerseId", "Position");

                    b.ToTable("verse_words", (string)null);
                });

            modelBuilder.Entity("StrongKingJames.Data.Entities.NoteEmbedding", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.HasKey("NoteId");

                    b.ToTable("note_embeddings", (string)null);
                });

            modelBuilder.Entity("StrongKingJames.Data.Entities.VerseEmbedding", b =>
                {
                    b.Property<int>("VerseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerseId"));

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.HasKey("VerseId");

                    b.ToTable("verse_embeddings", (string)null);
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.Verse", b =>
                {
                    b.HasOne("StrongKingJames.Core.Models.Book", "Book")
                        .WithMany("Verses")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.VerseWord", b =>
                {
                    b.HasOne("StrongKingJames.Core.Models.Verse", null)
                        .WithMany("Words")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StrongKingJames.Data.Entities.NoteEmbedding", b =>
                {
                    b.HasOne("StrongKingJames.Core.Models.Note", null)
                        .WithOne()
                        .HasForeignKey("StrongKingJames.Data.Entities.NoteEmbedding", "NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.Book", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("StrongKingJames.Core.Models.Verse", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
